name: WATTE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal
  - numpy
  - pandas
  - geopandas
  - rasterio
  - scipy
  - pip
 # - pip:
 #         - lidario==0.3.0
 #         - osgeo==0.0.1
