name: WATTE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal
  - numpy
  - pandas
  - geopandas
  - rasterio
  - scipy
  - pip
  - pip:
    - netCDF4
    - h5netcdf
    - xarray
 #         - lidario==0.3.0
 #         - osgeo==0.0.1
